### ISSUE TITLE
very_good_analysis

### ISSUE THREAD

**Issue by cem256** [furkanagess/book_app#7]
I noticed that you have imported the package `very_good_analysis` in the `pubspec.yaml` file. However, in order to use it effectively you have to add this code to your ` analysis_options.yaml` file

```
include: package:very_good_analysis/analysis_options.5.0.0.yaml

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
```
